[mqtt]
broker_address = "localhost"
port           = 18884
topic          = "mysuru"
machine_id     = '987654321'
keepalive      = 60

[mqtt.ssl]
ca_certs     = "tls/ca.pem"
client_certs = "tls/client-cert.pem"
client_key   = "tls/client-key.pem"
