[mqtt]
# The IP address or domain name, of the MQTT broker.
# Data type: string.
broker_address = "localhost"

# The port number at which the MQTT broker runs.
# Data type: string.
port = 1884

# The topic to subscribe to. This could include single-level or multi-level wildcards.
# Data type: string.
topic_prefix = "ABC City/#"

# The unique identifier for this machine. Used to authenticate with the MQTT broker and nothing else.
# Data type: string.
machine_id = "987654321"

# Specifies the keep alive interval for the client session. This is the maximum time that should
# pass without communication between the client and server.
# Data type: integer.
# Unit: seconds.
keepalive = 60

# Optional TLS connection settings.
# To disable TLS for the connection, comment out the following section, including the `[mqtt.ssl]`
# line.
# [mqtt.ssl]
# Path to file (file should be in PEM format) containing the public digital certificates trusted by
# the client. In other words, this specifies the path to the CA certificates file.
# Data type: string.
# ca_certs = "ca.pem"

# Path to the file (file should be in PEM format) containing the public certificate chain of the
# client.
# Data type: string.
# client_certs = "client-cert.pem"

# Path to the file (file should be in PEM format) containing the client's private key.
# Data type: string.
# client_key = "client-key.pem"

# Optional Telegram notification settings.
# To disable Telegram notifications, comment out the following section, including the
# `[notifications.telegram]` line.
# [notifications.telegram]
# The Telegram bot token. Obtain this by messaging `@BotFather` on Telegram.
# Data type: string.
# bot_token = "123456789:VeRyS3cRe7t0K3N"

# Telegram chat or channel ID to send notifications to.
# Data type: string.
# chat_id = "-1001234567890"

# Number of worker threads to use for handling Telegram notifications.
# Data type: integer.
# workers = 4

# Optional OneSignal notification settings.
# To disable OneSignal notifications, comment out the following section, including the
# `[notifications.onesignal]` line.
[notifications.onesignal]
# The OneSignal app ID. This is available under your app settings on the OneSignal dashboard, under
# the "Keys & IDs" tab.
# Data type: string.
app_id = "8250eaf6-1a58-489e-b136-7c74a864b434"

# The OneSignal REST API key. This is available under your app settings on the OneSignal dashboard,
# under the "Keys & IDs" tab.
api_key = "pi6KcVaJ2iSddaKp5gT2QKHrM7WkrdXjunVci3XA42iHKuCA"
