threshold_distance = 10
delay              = 2

[machine]
id       = "123456789"
location = "Mysuru"

[mqtt]
broker_url          = "tcp://localhost:1883"
topic               = "mysuru"
qos                 = 2
buffer_size         = 10
keep_alive_interval = 60
connect_timeout     = 30
min_retry_interval  = 5
max_retry_interval  = 60
